
"use client "

import CustomNavbar from "../components/CustomNavbar";
import "./globals.css";
import Footer from "../components/Footer";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import UserProvider from "../context/userProvider";
import AuthGate from "../components/AuthGate";



// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };


export default function RootLayout({ children }) {
  
  return (
    <html lang="en">
      <body className={`min-h-screen flex flex-col`}>
          <UserProvider>
            <AuthGate>
                        <ToastContainer
          position="top-right"
          autoClose={2000}
          theme="light"
          toastClassName="text-xs"
          toastStyle={{
            width: "220px",
            minHeight: "50px",
            padding: "8px",
            marginTop:"60px",
            marginRight:"100px",
            borderRadius:"5px",
            color:"black",
            fontWeight:"normal"

          }}
        />
        <CustomNavbar />
        <main className="flex-grow">{children}</main>

        {/* <Footer /> */}
            </AuthGate>
        </UserProvider>
      </body>
    </html>
  );
}
